### ISSUE TITLE
Error: It is related to yarn

### ISSUE THREAD

**Issue by ywzhaiqi** [clinyong/dll-link-webpack-plugin#3]
Error Message

	Error: ENOENT: no such file or directory, stat 'XXX\yarn.lock'
	    at Object.fs.statSync (fs.js:953:11)
	    at Object.statSync (XXX\node_modules\graceful-fs\polyfills.js:297:22)
	    at CacheController.checkCache (XXX\node_modules\dll-link-webpack-plugin\dist\CacheController.js:35:28)
	    at new CacheController (XXX\node_modules\dll-link-webpack-plugin\dist\CacheController.js:14:14)
	    at new DllLinkWebpackPlugin (XXX\node_modules\dll-link-webpack-plugin\dist\index.js:70:32)

my project not use yarn.

**Comment by clinyong** [comment]
It must be used with yarn.
